services:
  pr0:
    container_name: pr0
    image: hashicorp/vault-enterprise:${VERSION:-latest}
    volumes:
      - ./pr-configs/config0.hcl:/vault/config/config.hcl
      - ./data/data0:/opt/vault/data
      - ./logs/vault.log:/vault/logs/vault.log
    ports:
      - "8212:8212"
    cap_add:
      - "IPC_LOCK"
    env_file:
      - ../license.env
    environment:
      - VAULT_ADDR=http://127.0.0.1:8212
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.211.16:24224
        tag: "{{.Name}}"
        fluentd-async: "true"
    networks:
      vaulty-net:
        ipv4_address: 192.168.211.8
    command: server
  pr1:
    container_name: pr1
    image: hashicorp/vault-enterprise:${VERSION:-latest}
    volumes:
      - ./pr-configs/config1.hcl:/vault/config/config.hcl
      - ./data/data1:/opt/vault/data
      - ./logs/vault.log:/vault/logs/vault.log
    ports:
      - "8214:8214"
    cap_add:
      - "IPC_LOCK"
    env_file:
      - ../license.env
    environment:
      - VAULT_ADDR=http://127.0.0.1:8214
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.211.16:24224
        tag: "{{.Name}}"
        fluentd-async: "true"
    networks:
      vaulty-net:
        ipv4_address: 192.168.211.9
    command: server
  pr2:
    container_name: pr2
    image: hashicorp/vault-enterprise:${VERSION:-latest}
    volumes:
      - ./pr-configs/config2.hcl:/vault/config/config.hcl
      - ./data/data2:/opt/vault/data
      - ./logs/vault.log:/vault/logs/vault.log     
    ports:
      - "8216:8216"
    cap_add:
      - "IPC_LOCK"
    env_file:
      - ../license.env
    environment:
      - VAULT_ADDR=http://127.0.0.1:8216
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.211.16:24224
        tag: "{{.Name}}"
        fluentd-async: "true"
    networks:
      vaulty-net:
        ipv4_address: 192.168.211.10
    command: server
networks:
  vaulty-net:
    name: vaulty-net
    external: true